// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layer } from "./Layer";

export type Borders = { layer0: Array<Layer> | null, layer1: Array<Layer> | null, };
