// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Description } from "./Description";
import type { Rarity } from "./Rarity";
import type { SkinAugments } from "./SkinAugments";

export type Chroma = { id: bigint, name: string, chromaPath: string, colors: Array<string>, descriptions: Array<Description>, rarities: Array<Rarity>, skinAugments: SkinAugments | null, };
