// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegionEnum = "" | "ID" | "PH" | "tencent" | "riot" | "SG" | "TENCENT" | "TH" | "TW" | "VN";
