// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Description } from "./Description";
import type { Rarity } from "./Rarity";

export type SummonerIcon = { id: bigint, title: string, yearReleased: bigint, isLegacy: boolean, imagePath: string | null, descriptions: Array<Description>, rarities: Array<Rarity>, disabledRegions: Array<string>, esportsTeam: string | null, esportsRegion: string | null, esportsEvent: string | null, };
