// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BannerFlag } from "./BannerFlag";
import type { BannerFrame } from "./BannerFrame";

export type SummonerBanners = { BannerFlags: Array<BannerFlag>, BannerFrames: Array<BannerFrame>, };
