// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TypeField = "Boost" | "Chest" | "Companion" | "Currency" | "Material" | "Skin" | "Skin_Rental" | "Statstone" | "Statstone_Shard" | "SummonerIcon" | "TFT_Damage_Skin" | "TFT_Map_Skin" | "WardSkin";
