// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WardSkinSet = { id: bigint, hidden: boolean, displayName: string, description: string, wards: Array<bigint>, };
