// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Overlay } from "./Overlay";

export type Augment = { contentId: string, overlays: Array<Overlay>, };
