// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BannerFlag = { level: bigint, theme: string, name: string, inventoryIcon: string, profileIcon: string, };
