// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionEnum } from "./RegionEnum";

export type Description = { region: RegionEnum, description: string, };
