// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LootBundle } from "./LootBundle";
import type { LootItem } from "./LootItem";
import type { LootRecipe } from "./LootRecipe";
import type { LootTable } from "./LootTable";
import type { LootTokenBankCard } from "./LootTokenBankCard";

export type Loot = { LootItems: Array<LootItem>, LootRecipes: Array<LootRecipe>, LootTables: Array<LootTable>, LootBundles: Array<LootBundle>, LootTokenBankCards: Array<LootTokenBankCard>, };
