// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LootTokenBankCard = { lootItemName: string, backsplashImagePath: string, buttonText: string, nonPremiumCapCurrencyId: string, premiumCapCurrencyId: string, titleText: string, tokenIconPath: string, tooltipDescriptionText: string, tooltipSplashPath: string, tooltipTitleText: string, unlockItemId: string, unlockItemType: string, activationDate: string, deactivationDate: string, storeLinkItem: string, storeLinkType: string, };
