// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RarityField } from "./RarityField";
import type { TypeField } from "./TypeField";

export type LootItem = { id: string, name: string, description: string, image: string, startDate: string, endDate: string, mappedStoreId: bigint, lifetimeMax: bigint, autoRedeem: boolean, rarity: RarityField, type: TypeField, recipeMenuActive: string | null, recipeMenuTitle: string | null, recipeMenuSubtitle: string | null, };
