// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Content } from "./Content";

export type LootBundle = { id: string, description: string, descriptionLong: string, image: string, contents: Array<Content>, };
