// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DropChance } from "./DropChance";

export type LootTable = { id: string, description: string, descriptionLong: string, image: string, dropChance: Array<DropChance>, };
