// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Output } from "./Output";

export type LootRecipe = { id: string, description: string, contextMenuText: string, requirementText: string, imagePath: string, introVideoPath: string, loopVideoPath: string, outroVideoPath: string, hasVisibleLootOdds: boolean, outputs: Array<Output>, };
