// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DescriptionInfo } from "./DescriptionInfo";
import type { Tier } from "./Tier";

export type QuestSkinInfo = { name: string, productType: string, collectionDescription: string, descriptionInfo: Array<DescriptionInfo>, splashPath: string, uncenteredSplashPath: string, tilePath: string, collectionCardPath: string, tiers: Array<Tier>, };
