// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Augment } from "./Augment";
import type { Borders } from "./Borders";

export type SkinAugments = { borders: Borders, augments: Array<Augment> | null, };
