// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chroma } from "./Chroma";
import type { QuestSkinInfo } from "./QuestSkinInfo";
import type { RarityEnum } from "./RarityEnum";
import type { SkinAugments } from "./SkinAugments";
import type { SkinLineId } from "./SkinLineId";
import type { SkinType } from "./SkinType";

export type Skin = { id: bigint, isBase: boolean, name: string, splashPath: string, uncenteredSplashPath: string, tilePath: string, loadScreenPath: string, loadScreenVintagePath: string | null, skinType: SkinType, rarity: RarityEnum, isLegacy: boolean, splashVideoPath: string | null, collectionSplashVideoPath: string | null, collectionCardHoverVideoPath: string | null, featuresText: string | null, chromaPath: string | null, emblems: string | null, regionRarityId: bigint, rarityGemPath: string | null, skinLines: Array<SkinLineId> | null, description: string | null, chromas: Array<Chroma> | null, skinAugments: SkinAugments | null, questSkinInfo: QuestSkinInfo | null, };
