// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummonerEmote = { id: bigint, name: string, inventoryIcon: string, description: string, };
