// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinAugments } from "./SkinAugments";

export type Tier = { id: bigint, name: string, stage: bigint, description: string, splashPath: string, uncenteredSplashPath: string, tilePath: string, loadScreenPath: string, shortName: string, splashVideoPath: string | null, collectionSplashVideoPath: string | null, collectionCardHoverVideoPath: string | null, skinAugments: SkinAugments | null, loadScreenVintagePath: string | null, };
