// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rarity } from "./Rarity";
import type { RegionalDescription } from "./RegionalDescription";

export type WardSkin = { id: bigint, name: string, description: string, wardImagePath: string, wardShadowImagePath: string, isLegacy: boolean, regionalDescriptions: Array<RegionalDescription>, rarities: Array<Rarity>, };
