name: Scheduled publish

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*
  schedule:
    - cron: '5 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          
      - name: Add NPM User
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Generate & Publish
        run: |
          npm install
          ./scripts/publish.sh
          echo "CURR_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Git add & commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'VERSION'
          default_author: github_actions
          message: "chore: publish version ${{ env.CURR_VERSION }}"

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            save/*
