name: Scheduled publish

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*
  schedule:
    - cron: '5 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Add NPM User
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Generate & Publish
        run: |
          npm install
          ./scripts/publish.sh

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            save/*
