name: Scheduled publish

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*
  schedule:
    - cron: '5 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout to latest tag
        run: |
          git fetch --prune --unshallow
          latestTag=$(git describe --tags --abbrev=0)
          git checkout tags/$latestTag
          echo "current version: $latestTag"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Generate & Publish
        run: |
          npx npm-cli-adduser -u ${{ secrets.NPM_USER }} -e ${{ secrets.NPM_EMAIL }} -p ${{ secrets.NPM_PASS }}
          ./scripts/publish.sh

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            save/*